dist: xenial

sudo: required

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - git clone https://github.com/catchorg/Catch2.git
  - cmake -BCatch2/build -HCatch2 -DBUILD_TESTING=OFF
  - sudo env "PATH=$PATH" cmake --build Catch2/build/ --target install

script:
  - >
    cmake .
    -Bbuild
    -DBUILD_TESTING:BOOL=ON
