image: Visual Studio 2017

install:
- vcpkg install catch2

configuration:
- Debug
- Release

environment:
  matrix:
  - VS_TYPE: Visual Studio 14 2015
  - VS_TYPE: Visual Studio 15 2017

before_build:
- mkdir build

build_script:
- >
  cmake .
  -Bbuild
  -G "%VS_TYPE%"
  -DBUILD_TESTING:BOOL=ON
  -DCMAKE_BUILD_TYPE:STRING=%configuration%
  -DCMAKE_TOOLCHAIN_FILE="C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
- >
  cmake
  --build build
  --config %configuration%

test_script:
- cd build
- ctest -C %configuration%

cache: C:/tools/vcpkg/installed/
