version: 2.1

commands:
  build_parameterized:
    parameters:
      compiler:
        default: "g++"
        description: The C++ compiler.
        type: enum
        enum: ["clang++", "g++"]
      cxx:
        default: "14"
        description: The C++ standard version.
        type: enum
        enum: ["03", "11", "14", "17"]
    steps:
      - checkout
      - run:
          name: Update apt
          command: 'apt update'
      - run:
          name: Install build tools
          command: 'apt install -y clang g++ cmake git'
      - run:
          name: Install dependencies
          command: |
            git clone https://github.com/catchorg/Catch2.git
            cmake -BCatch2/build -HCatch2 -DBUILD_TESTING=OFF
            cmake --build Catch2/build/ --target install
      - run:
          name: Create build files
          command: >
              cmake
              -H.
              -Bbuild
              -DBUILD_TESTING:BOOL=ON
              -DCMAKE_BUILD_TYPE:STRING=Debug
              -DCMAKE_CXX_COMPILER=<< parameters.compiler >>
              -DCMAKE_CXX_STANDARD=<< parameters.cxx >>
      - run:
          name: Build code
          command: >
              cmake
              --build build
              --config Debug
      - run:
          name: Run tests
          command: |
            cd build
            ctest -C Debug

jobs:
  build_clang_14:
    docker:
      - image: "debian:sid"
    steps:
      - build_parameterized:
          compiler: "clang++"
          cxx: "14"
  build_gcc_14:
    docker:
      - image: "debian:sid"
    steps:
      - build_parameterized:
          compiler: "g++"
          cxx: "14"
  build_gcc_17:
    docker:
      - image: "debian:sid"
    steps:
      - build_parameterized:
          compiler: "g++"
          cxx: "17"

workflows:
  version: 2
  build_all:
    jobs:
      - build_clang_14
      - build_gcc_14
      - build_gcc_17
